In [476]:
import numpy as np
import pandas as pd
import os

In [477]:
train_df = pd.read_csv("/train.csv")
test_df = pd.read_csv("/test.csv")

In [478]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [479]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [480]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [481]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [482]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [483]:
def clean_data(data):
    data['Fare'] = data['Fare'].fillna(data['Fare'].dropna().median())
    data['Age'] =  data['Age'].fillna(data['Age'].dropna().median())

    data.loc[data['Sex'] == 'male', 'Sex'] = 0
    data.loc[data['Sex'] =='female',  'Sex'] = 1

    data['Embarked'] = data['Embarked'].fillna('S')
    data.loc[data["Embarked"] == 'S', 'Embarked'] = 0
    data.loc[data['Embarked'] == 'C', 'Embarked'] = 1
    data.loc[data['Embarked'] == 'Q', 'Embarked'] =2

In [484]:
def write_prediction(prediction, name):
    PassengerId = np.array(test['PassengerId']).astype(int)
    solution = pd.DataFrame(prediction, PassengerId, columns = ['Survived'])
    solution.to_csv(name, index_label = ['PassengerId'])

In [485]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [486]:
clean_data(train_df)
clean_data(test_df)

In [487]:
drop_column = ['Cabin']
train_df.drop(drop_column, axis=1, inplace = True)
test_df.drop(drop_column,axis=1,inplace=True)

In [488]:
train_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [489]:
test_df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [490]:
all_data=[train_df,test_df]

In [491]:
for dataset in all_data:
    dataset['FamilySize'] = dataset['SibSp'] + dataset['Parch'] + 1

In [492]:
import re

def get_title(name):
    title_search = re.search(' ([A-Za-z]+)\.', name)
    # If the title exists, extract and return it.
    if title_search:
        return title_search.group(1)
    return ""
# Create a new feature Title, containing the titles of passenger names
for dataset in all_data:
    dataset['Title'] = dataset['Name'].apply(get_title)
# Group all non-common titles into one single grouping "Rare"
for dataset in all_data:
    dataset['Title'] = dataset['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don',
                                                 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')

    dataset['Title'] = dataset['Title'].replace('Mlle', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Ms', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Mme', 'Mrs')

In [493]:

for dataset in all_data:
    dataset['Age_bin'] = pd.cut(dataset['Age'], bins=[0,12,20,40,120], labels=['Children','Teenage','Adult','Elder'])

In [494]:

for dataset in all_data:
    dataset['Fare_bin'] = pd.cut(dataset['Fare'], bins=[0,7.91,14.45,31,120], labels=['Low_fare','median_fare',
                                                                                      'Average_fare','high_fare'])

In [495]:
traindf=train_df
testdf=test_df

In [496]:
all_dat=[traindf,testdf]

In [497]:
for dataset in all_dat:
    drop_column = ['Age','Fare','Name','Ticket']
    dataset.drop(drop_column, axis=1, inplace = True)

In [498]:
drop_column = ['PassengerId']
traindf.drop(drop_column, axis=1, inplace = True)

In [499]:
testdf.head()

,PassengerId,Pclass,Sex,SibSp,Parch,Embarked,FamilySize,Title,Age_bin,Fare_bin
0,892,3,0,0,0,2,1,Mr,Adult,Low_fare
1,893,3,1,1,0,0,2,Mrs,Elder,Low_fare
2,894,2,0,0,0,2,1,Mr,Elder,median_fare
3,895,3,0,0,0,0,1,Mr,Adult,median_fare
4,896,3,1,1,1,0,3,Mrs,Adult,median_fare

In [500]:
traindf= pd.get_dummies(traindf, columns = ["Sex","Title","Age_bin","Embarked","Fare_bin"],
                             prefix=["Sex","Title","Age_type","Em_type","Fare_type"])

<ipython-input-500-e3440c50a084>:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  traindf= pd.get_dummies(traindf, columns = ["Sex","Title","Age_bin","Embarked","Fare_bin"],
<ipython-input-500-e3440c50a084>:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  traindf= pd.get_dummies(traindf, columns = ["Sex","Title","Age_bin","Embarked","Fare_bin"],

In [501]:
testdf = pd.get_dummies(testdf, columns = ["Sex","Title","Age_bin","Embarked","Fare_bin"],
                             prefix=["Sex","Title","Age_type","Em_type","Fare_type"])

<ipython-input-501-539ba8394544>:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  testdf = pd.get_dummies(testdf, columns = ["Sex","Title","Age_bin","Embarked","Fare_bin"],
<ipython-input-501-539ba8394544>:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  testdf = pd.get_dummies(testdf, columns = ["Sex","Title","Age_bin","Embarked","Fare_bin"],

In [502]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
all_features = traindf.drop("Survived",axis=1)
Targeted_feature = traindf["Survived"]
X_train,X_test,y_train,y_test = train_test_split(all_features,Targeted_feature,test_size=0.3,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((623, 22), (268, 22), (623,), (268,))

**MACHINE LEARNING MODEL**

In [503]:
# Support Vector Machines
from sklearn.svm import SVC, LinearSVC

model = SVC()
model.fit(X_train,y_train)
prediction_svm=model.predict(X_test)
print('--------------The Accuracy of the model----------------------------')
print('The accuracy of the Support Vector Machines Classifier is',round(accuracy_score(prediction_svm,y_test)*100,2))
kfold = KFold(n_splits=10)
result_svm=cross_val_score(model,all_features,Targeted_feature,cv=10,scoring='accuracy')
print('The cross validated score for Support Vector Machines Classifier is:',round(result_svm.mean()*100,2))
y_pred = cross_val_predict(model,all_features,Targeted_feature,cv=10)

--------------The Accuracy of the model----------------------------
The accuracy of the Support Vector Machines Classifier is 83.58
The cross validated score for Support Vector Machines Classifier is: 83.16

**Deep Learning Model**

In [504]:
target = traindf['Survived'].values
features = traindf[['Pclass','SibSp','Parch','FamilySize','Sex_0','Sex_1','Title_Master','Title_Miss','Title_Mr','Title_Mrs','Title_Rare','Age_type_Children','Age_type_Teenage','Age_type_Adult','Age_type_Elder','Em_type_0','Em_type_1','Em_type_2','Fare_type_Low_fare','Fare_type_median_fare','Fare_type_Average_fare','Fare_type_high_fare']].values

In [505]:
import keras

In [506]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

classifier = Sequential()
classifier.add(Dense(activation="relu", input_dim=22, units=11, kernel_initializer="uniform"))
classifier.add(Dense(activation="relu", units=11, kernel_initializer="uniform"))
classifier.add(Dropout(0.5))
classifier.add(Dense(activation="relu", units=11, kernel_initializer="uniform"))
classifier.add(Dropout(0.5))
classifier.add(Dense(activation="relu", units=5, kernel_initializer="uniform"))
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_20 (Dense)            (None, 11)                253

 dense_21 (Dense)            (None, 11)                132

 dropout_8 (Dropout)         (None, 11)                0

 dense_22 (Dense)            (None, 11)                132

 dropout_9 (Dropout)         (None, 11)                0

 dense_23 (Dense)            (None, 5)                 60

 dense_24 (Dense)            (None, 1)                 6

=================================================================
Total params: 583
Trainable params: 583
Non-trainable params: 0
_________________________________________________________________

In [507]:
history = classifier.fit(features, target, batch_size=10, epochs=100,
                         validation_split=0.1, verbose=1, shuffle=True)

Epoch 1/100
81/81 [==============================] - 2s 7ms/step - loss: 0.6905 - accuracy: 0.6117 - val_loss: 0.6866 - val_accuracy: 0.6222
Epoch 2/100
81/81 [==============================] - 0s 3ms/step - loss: 0.6748 - accuracy: 0.6155 - val_loss: 0.6386 - val_accuracy: 0.6222
Epoch 3/100
81/81 [==============================] - 0s 3ms/step - loss: 0.6085 - accuracy: 0.6155 - val_loss: 0.5605 - val_accuracy: 0.6222
Epoch 4/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5671 - accuracy: 0.6155 - val_loss: 0.5277 - val_accuracy: 0.6222
Epoch 5/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5620 - accuracy: 0.6155 - val_loss: 0.5100 - val_accuracy: 0.6222
Epoch 6/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5545 - accuracy: 0.6841 - val_loss: 0.5051 - val_accuracy: 0.8000
Epoch 7/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5447 - accuracy: 0.7803 - val_loss: 0.4989 - val_accuracy: 0.8111
Epoch 8/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5503 - accuracy: 0.7928 - val_loss: 0.5065 - val_accuracy: 0.8222
Epoch 9/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5448 - accuracy: 0.8052 - val_loss: 0.4935 - val_accuracy: 0.8111
Epoch 10/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5506 - accuracy: 0.7928 - val_loss: 0.4889 - val_accuracy: 0.8222
Epoch 11/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5597 - accuracy: 0.7853 - val_loss: 0.4908 - val_accuracy: 0.8222
Epoch 12/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5399 - accuracy: 0.8015 - val_loss: 0.4793 - val_accuracy: 0.8333
Epoch 13/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5427 - accuracy: 0.8102 - val_loss: 0.4830 - val_accuracy: 0.8333
Epoch 14/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5533 - accuracy: 0.7978 - val_loss: 0.4813 - val_accuracy: 0.8333
Epoch 15/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5290 - accuracy: 0.7965 - val_loss: 0.4758 - val_accuracy: 0.8222
Epoch 16/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5435 - accuracy: 0.8090 - val_loss: 0.4731 - val_accuracy: 0.8333
Epoch 17/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5317 - accuracy: 0.7990 - val_loss: 0.4819 - val_accuracy: 0.8222
Epoch 18/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5316 - accuracy: 0.7940 - val_loss: 0.4725 - val_accuracy: 0.8333
Epoch 19/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5484 - accuracy: 0.8102 - val_loss: 0.4796 - val_accuracy: 0.8333
Epoch 20/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5447 - accuracy: 0.8090 - val_loss: 0.4791 - val_accuracy: 0.8444
Epoch 21/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4973 - accuracy: 0.8102 - val_loss: 0.4588 - val_accuracy: 0.8333
Epoch 22/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5264 - accuracy: 0.8015 - val_loss: 0.4771 - val_accuracy: 0.8222
Epoch 23/100
81/81 [==============================] - 0s 6ms/step - loss: 0.5313 - accuracy: 0.7940 - val_loss: 0.4636 - val_accuracy: 0.8444
Epoch 24/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5201 - accuracy: 0.7990 - val_loss: 0.4619 - val_accuracy: 0.8333
Epoch 25/100
81/81 [==============================] - 0s 6ms/step - loss: 0.5396 - accuracy: 0.7978 - val_loss: 0.4595 - val_accuracy: 0.8333
Epoch 26/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5131 - accuracy: 0.8115 - val_loss: 0.4561 - val_accuracy: 0.8222
Epoch 27/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5223 - accuracy: 0.8052 - val_loss: 0.4655 - val_accuracy: 0.8556
Epoch 28/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5187 - accuracy: 0.7953 - val_loss: 0.4513 - val_accuracy: 0.8333
Epoch 29/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5264 - accuracy: 0.8015 - val_loss: 0.4650 - val_accuracy: 0.8444
Epoch 30/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5122 - accuracy: 0.8040 - val_loss: 0.4560 - val_accuracy: 0.8556
Epoch 31/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5186 - accuracy: 0.7853 - val_loss: 0.4567 - val_accuracy: 0.8556
Epoch 32/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5267 - accuracy: 0.7990 - val_loss: 0.4622 - val_accuracy: 0.8333
Epoch 33/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5168 - accuracy: 0.7978 - val_loss: 0.4630 - val_accuracy: 0.8333
Epoch 34/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5218 - accuracy: 0.8040 - val_loss: 0.4750 - val_accuracy: 0.8333
Epoch 35/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5098 - accuracy: 0.8052 - val_loss: 0.4557 - val_accuracy: 0.8333
Epoch 36/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5011 - accuracy: 0.8115 - val_loss: 0.4455 - val_accuracy: 0.8444
Epoch 37/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5070 - accuracy: 0.7965 - val_loss: 0.4520 - val_accuracy: 0.8333
Epoch 38/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4916 - accuracy: 0.8177 - val_loss: 0.4488 - val_accuracy: 0.8444
Epoch 39/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5237 - accuracy: 0.7928 - val_loss: 0.4512 - val_accuracy: 0.8444
Epoch 40/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5127 - accuracy: 0.7940 - val_loss: 0.4416 - val_accuracy: 0.8444
Epoch 41/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5124 - accuracy: 0.7940 - val_loss: 0.4536 - val_accuracy: 0.8444
Epoch 42/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5231 - accuracy: 0.7928 - val_loss: 0.4496 - val_accuracy: 0.8444
Epoch 43/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5104 - accuracy: 0.7965 - val_loss: 0.4512 - val_accuracy: 0.8444
Epoch 44/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5085 - accuracy: 0.7990 - val_loss: 0.4429 - val_accuracy: 0.8556
Epoch 45/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5143 - accuracy: 0.8027 - val_loss: 0.4434 - val_accuracy: 0.8556
Epoch 46/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5127 - accuracy: 0.7928 - val_loss: 0.4447 - val_accuracy: 0.8444
Epoch 47/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5264 - accuracy: 0.7965 - val_loss: 0.4548 - val_accuracy: 0.8333
Epoch 48/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5093 - accuracy: 0.8052 - val_loss: 0.4535 - val_accuracy: 0.8333
Epoch 49/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5309 - accuracy: 0.7865 - val_loss: 0.4673 - val_accuracy: 0.8333
Epoch 50/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5125 - accuracy: 0.7915 - val_loss: 0.4433 - val_accuracy: 0.8556
Epoch 51/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5003 - accuracy: 0.8040 - val_loss: 0.4363 - val_accuracy: 0.8333
Epoch 52/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5048 - accuracy: 0.7990 - val_loss: 0.4391 - val_accuracy: 0.8444
Epoch 53/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5107 - accuracy: 0.7953 - val_loss: 0.4396 - val_accuracy: 0.8556
Epoch 54/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5061 - accuracy: 0.8052 - val_loss: 0.4419 - val_accuracy: 0.8556
Epoch 55/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5138 - accuracy: 0.8002 - val_loss: 0.4487 - val_accuracy: 0.8556
Epoch 56/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5144 - accuracy: 0.7890 - val_loss: 0.4411 - val_accuracy: 0.8556
Epoch 57/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4984 - accuracy: 0.8002 - val_loss: 0.4353 - val_accuracy: 0.8333
Epoch 58/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4998 - accuracy: 0.7990 - val_loss: 0.4327 - val_accuracy: 0.8556
Epoch 59/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5074 - accuracy: 0.7953 - val_loss: 0.4524 - val_accuracy: 0.8444
Epoch 60/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4993 - accuracy: 0.7965 - val_loss: 0.4421 - val_accuracy: 0.8333
Epoch 61/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5213 - accuracy: 0.8002 - val_loss: 0.4428 - val_accuracy: 0.8444
Epoch 62/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4983 - accuracy: 0.8102 - val_loss: 0.4406 - val_accuracy: 0.8444
Epoch 63/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5083 - accuracy: 0.7953 - val_loss: 0.4432 - val_accuracy: 0.8333
Epoch 64/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4962 - accuracy: 0.8052 - val_loss: 0.4522 - val_accuracy: 0.8333
Epoch 65/100
81/81 [==============================] - 0s 6ms/step - loss: 0.5025 - accuracy: 0.8152 - val_loss: 0.4411 - val_accuracy: 0.8333
Epoch 66/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4802 - accuracy: 0.8115 - val_loss: 0.4431 - val_accuracy: 0.8444
Epoch 67/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4901 - accuracy: 0.8015 - val_loss: 0.4432 - val_accuracy: 0.8222
Epoch 68/100
81/81 [==============================] - 1s 6ms/step - loss: 0.5089 - accuracy: 0.8077 - val_loss: 0.4665 - val_accuracy: 0.8333
Epoch 69/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5073 - accuracy: 0.8127 - val_loss: 0.4451 - val_accuracy: 0.8333
Epoch 70/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4874 - accuracy: 0.8052 - val_loss: 0.4346 - val_accuracy: 0.8444
Epoch 71/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4934 - accuracy: 0.7990 - val_loss: 0.4325 - val_accuracy: 0.8444
Epoch 72/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5022 - accuracy: 0.8027 - val_loss: 0.4486 - val_accuracy: 0.8333
Epoch 73/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5014 - accuracy: 0.8115 - val_loss: 0.4478 - val_accuracy: 0.8111
Epoch 74/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5044 - accuracy: 0.8077 - val_loss: 0.4495 - val_accuracy: 0.8333
Epoch 75/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4991 - accuracy: 0.8140 - val_loss: 0.4369 - val_accuracy: 0.8444
Epoch 76/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5103 - accuracy: 0.8015 - val_loss: 0.4498 - val_accuracy: 0.8444
Epoch 77/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4848 - accuracy: 0.8127 - val_loss: 0.4318 - val_accuracy: 0.8444
Epoch 78/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5018 - accuracy: 0.7978 - val_loss: 0.4468 - val_accuracy: 0.8444
Epoch 79/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5054 - accuracy: 0.7978 - val_loss: 0.4239 - val_accuracy: 0.8556
Epoch 80/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5017 - accuracy: 0.7990 - val_loss: 0.4223 - val_accuracy: 0.8556
Epoch 81/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4838 - accuracy: 0.8115 - val_loss: 0.4304 - val_accuracy: 0.8667
Epoch 82/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4918 - accuracy: 0.7978 - val_loss: 0.4356 - val_accuracy: 0.8667
Epoch 83/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4827 - accuracy: 0.8140 - val_loss: 0.4265 - val_accuracy: 0.8444
Epoch 84/100
81/81 [==============================] - 0s 3ms/step - loss: 0.5005 - accuracy: 0.7990 - val_loss: 0.4422 - val_accuracy: 0.8556
Epoch 85/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4807 - accuracy: 0.8190 - val_loss: 0.4222 - val_accuracy: 0.8444
Epoch 86/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4965 - accuracy: 0.8077 - val_loss: 0.4571 - val_accuracy: 0.8333
Epoch 87/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4806 - accuracy: 0.7940 - val_loss: 0.4290 - val_accuracy: 0.8444
Epoch 88/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4895 - accuracy: 0.8102 - val_loss: 0.4395 - val_accuracy: 0.8444
Epoch 89/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4890 - accuracy: 0.8090 - val_loss: 0.4382 - val_accuracy: 0.8556
Epoch 90/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4805 - accuracy: 0.7990 - val_loss: 0.4209 - val_accuracy: 0.8667
Epoch 91/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5078 - accuracy: 0.8065 - val_loss: 0.4519 - val_accuracy: 0.8556
Epoch 92/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4958 - accuracy: 0.7953 - val_loss: 0.4429 - val_accuracy: 0.8556
Epoch 93/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4736 - accuracy: 0.8127 - val_loss: 0.4254 - val_accuracy: 0.8667
Epoch 94/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4922 - accuracy: 0.8015 - val_loss: 0.4287 - val_accuracy: 0.8667
Epoch 95/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4844 - accuracy: 0.8052 - val_loss: 0.4301 - val_accuracy: 0.8667
Epoch 96/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4917 - accuracy: 0.7978 - val_loss: 0.4314 - val_accuracy: 0.8667
Epoch 97/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4803 - accuracy: 0.8065 - val_loss: 0.4284 - val_accuracy: 0.8556
Epoch 98/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4794 - accuracy: 0.7915 - val_loss: 0.4333 - val_accuracy: 0.8556
Epoch 99/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4840 - accuracy: 0.8052 - val_loss: 0.4344 - val_accuracy: 0.8556
Epoch 100/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4786 - accuracy: 0.8115 - val_loss: 0.4372 - val_accuracy: 0.8556

In [508]:
drop_column = ['PassengerId']
testdf.drop(drop_column, axis=1, inplace = True)
testdf.head()

,Pclass,SibSp,Parch,FamilySize,Sex_0,Sex_1,Title_Master,Title_Miss,Title_Mr,Title_Mrs,...,Age_type_Teenage,Age_type_Adult,Age_type_Elder,Em_type_0,Em_type_1,Em_type_2,Fare_type_Low_fare,Fare_type_median_fare,Fare_type_Average_fare,Fare_type_high_fare
0,3,0,0,1,1,0,0,0,1,0,...,0,1,0,0,0,1,1,0,0,0
1,3,1,0,2,0,1,0,0,0,1,...,0,0,1,1,0,0,1,0,0,0
2,2,0,0,1,1,0,0,0,1,0,...,0,0,1,0,0,1,0,1,0,0
3,3,0,0,1,1,0,0,0,1,0,...,0,1,0,1,0,0,0,1,0,0
4,3,1,1,3,0,1,0,0,0,1,...,0,1,0,1,0,0,0,1,0,0

In [509]:

Y_pred = classifier.predict(testdf)

14/14 [==============================] - 0s 2ms/step

In [510]:
Y_pred.dtype

dtype('float32')

In [511]:

Y_pred=Y_pred.round()
Y_pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [512]:
write_prediction(Y_pred, "My_output.csv")

In [513]:
# ... (previous code)

# Training the model
history = classifier.fit(features, target, batch_size=10, epochs=100,
                         validation_split=0.1, verbose=1, shuffle=True)
#Calculate accuracy on the validation set

validation_accuracy = classifier.evaluate(features, target)[1]
print(f"Validation Accuracy: {validation_accuracy:.2%}")

# Making predictions
Y_pred = classifier.predict(testdf)
Y_pred = Y_pred.round()

# Create a DataFrame with predictions
predictions_df = pd.DataFrame(Y_pred, columns=['Survived'])

# Read the test.csv file to get passenger IDs
passenger_ids = pd.read_csv('/test.csv')['PassengerId']

# Concatenate passenger IDs and predictions
submission = pd.concat([passenger_ids, predictions_df], axis=1)

# Save the predictions and accuracy to a CSV file
submission.to_csv('My_output.csv', index=False)

Epoch 1/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4858 - accuracy: 0.8027 - val_loss: 0.4271 - val_accuracy: 0.8667
Epoch 2/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4897 - accuracy: 0.8052 - val_loss: 0.4374 - val_accuracy: 0.8556
Epoch 3/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4820 - accuracy: 0.8027 - val_loss: 0.4252 - val_accuracy: 0.8667
Epoch 4/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4982 - accuracy: 0.8052 - val_loss: 0.4445 - val_accuracy: 0.8444
Epoch 5/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4944 - accuracy: 0.8040 - val_loss: 0.4266 - val_accuracy: 0.8667
Epoch 6/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5156 - accuracy: 0.7928 - val_loss: 0.4580 - val_accuracy: 0.8333
Epoch 7/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5061 - accuracy: 0.7953 - val_loss: 0.4456 - val_accuracy: 0.8556
Epoch 8/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4967 - accuracy: 0.8040 - val_loss: 0.4482 - val_accuracy: 0.8444
Epoch 9/100
81/81 [==============================] - 0s 4ms/step - loss: 0.5178 - accuracy: 0.7965 - val_loss: 0.4459 - val_accuracy: 0.8556
Epoch 10/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4889 - accuracy: 0.8027 - val_loss: 0.4295 - val_accuracy: 0.8444
Epoch 11/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4898 - accuracy: 0.8027 - val_loss: 0.4431 - val_accuracy: 0.8556
Epoch 12/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4925 - accuracy: 0.7965 - val_loss: 0.4324 - val_accuracy: 0.8444
Epoch 13/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4957 - accuracy: 0.8115 - val_loss: 0.4326 - val_accuracy: 0.8444
Epoch 14/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4874 - accuracy: 0.8015 - val_loss: 0.4438 - val_accuracy: 0.8333
Epoch 15/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4669 - accuracy: 0.8127 - val_loss: 0.4404 - val_accuracy: 0.8333
Epoch 16/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4932 - accuracy: 0.7903 - val_loss: 0.4498 - val_accuracy: 0.8556
Epoch 17/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4900 - accuracy: 0.8190 - val_loss: 0.4278 - val_accuracy: 0.8444
Epoch 18/100
81/81 [==============================] - 1s 7ms/step - loss: 0.5096 - accuracy: 0.8027 - val_loss: 0.4611 - val_accuracy: 0.8444
Epoch 19/100
81/81 [==============================] - 1s 7ms/step - loss: 0.5000 - accuracy: 0.7890 - val_loss: 0.4314 - val_accuracy: 0.8444
Epoch 20/100
81/81 [==============================] - 1s 9ms/step - loss: 0.4576 - accuracy: 0.8152 - val_loss: 0.4238 - val_accuracy: 0.8444
Epoch 21/100
81/81 [==============================] - 1s 8ms/step - loss: 0.4718 - accuracy: 0.8127 - val_loss: 0.4283 - val_accuracy: 0.8556
Epoch 22/100
81/81 [==============================] - 1s 8ms/step - loss: 0.4635 - accuracy: 0.7928 - val_loss: 0.4237 - val_accuracy: 0.8444
Epoch 23/100
81/81 [==============================] - 1s 10ms/step - loss: 0.4928 - accuracy: 0.7853 - val_loss: 0.4389 - val_accuracy: 0.8556
Epoch 24/100
81/81 [==============================] - 1s 8ms/step - loss: 0.4914 - accuracy: 0.7978 - val_loss: 0.4343 - val_accuracy: 0.8556
Epoch 25/100
81/81 [==============================] - 1s 6ms/step - loss: 0.4893 - accuracy: 0.8015 - val_loss: 0.4362 - val_accuracy: 0.8556
Epoch 26/100
81/81 [==============================] - 1s 6ms/step - loss: 0.4770 - accuracy: 0.8015 - val_loss: 0.4309 - val_accuracy: 0.8556
Epoch 27/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4815 - accuracy: 0.8090 - val_loss: 0.4337 - val_accuracy: 0.8667
Epoch 28/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4758 - accuracy: 0.8202 - val_loss: 0.4313 - val_accuracy: 0.8556
Epoch 29/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4869 - accuracy: 0.7928 - val_loss: 0.4431 - val_accuracy: 0.8556
Epoch 30/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4934 - accuracy: 0.7828 - val_loss: 0.4366 - val_accuracy: 0.8556
Epoch 31/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4954 - accuracy: 0.7915 - val_loss: 0.4387 - val_accuracy: 0.8556
Epoch 32/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4898 - accuracy: 0.7978 - val_loss: 0.4536 - val_accuracy: 0.8333
Epoch 33/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4827 - accuracy: 0.7978 - val_loss: 0.4365 - val_accuracy: 0.8556
Epoch 34/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4885 - accuracy: 0.7965 - val_loss: 0.4359 - val_accuracy: 0.8556
Epoch 35/100
81/81 [==============================] - 1s 7ms/step - loss: 0.4784 - accuracy: 0.7953 - val_loss: 0.4367 - val_accuracy: 0.8556
Epoch 36/100
81/81 [==============================] - 1s 7ms/step - loss: 0.4697 - accuracy: 0.8165 - val_loss: 0.4391 - val_accuracy: 0.8556
Epoch 37/100
81/81 [==============================] - 1s 7ms/step - loss: 0.4950 - accuracy: 0.8027 - val_loss: 0.4598 - val_accuracy: 0.8444
Epoch 38/100
81/81 [==============================] - 1s 8ms/step - loss: 0.4802 - accuracy: 0.7928 - val_loss: 0.4397 - val_accuracy: 0.8556
Epoch 39/100
81/81 [==============================] - 1s 8ms/step - loss: 0.4891 - accuracy: 0.8077 - val_loss: 0.4380 - val_accuracy: 0.8333
Epoch 40/100
81/81 [==============================] - 1s 7ms/step - loss: 0.4759 - accuracy: 0.7903 - val_loss: 0.4397 - val_accuracy: 0.8556
Epoch 41/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4862 - accuracy: 0.7953 - val_loss: 0.4485 - val_accuracy: 0.8556
Epoch 42/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4931 - accuracy: 0.7815 - val_loss: 0.4434 - val_accuracy: 0.8444
Epoch 43/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4866 - accuracy: 0.8202 - val_loss: 0.4464 - val_accuracy: 0.8667
Epoch 44/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4725 - accuracy: 0.8052 - val_loss: 0.4476 - val_accuracy: 0.8444
Epoch 45/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4835 - accuracy: 0.7915 - val_loss: 0.4354 - val_accuracy: 0.8333
Epoch 46/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4798 - accuracy: 0.8040 - val_loss: 0.4374 - val_accuracy: 0.8444
Epoch 47/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4964 - accuracy: 0.7953 - val_loss: 0.4441 - val_accuracy: 0.8333
Epoch 48/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4720 - accuracy: 0.8227 - val_loss: 0.4463 - val_accuracy: 0.8333
Epoch 49/100
81/81 [==============================] - 1s 6ms/step - loss: 0.5058 - accuracy: 0.7940 - val_loss: 0.4534 - val_accuracy: 0.8333
Epoch 50/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4748 - accuracy: 0.8040 - val_loss: 0.4465 - val_accuracy: 0.8556
Epoch 51/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4788 - accuracy: 0.8027 - val_loss: 0.4509 - val_accuracy: 0.8556
Epoch 52/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4793 - accuracy: 0.7978 - val_loss: 0.4458 - val_accuracy: 0.8556
Epoch 53/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4545 - accuracy: 0.8240 - val_loss: 0.4315 - val_accuracy: 0.8333
Epoch 54/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4779 - accuracy: 0.7878 - val_loss: 0.4286 - val_accuracy: 0.8333
Epoch 55/100
81/81 [==============================] - 0s 5ms/step - loss: 0.5004 - accuracy: 0.8015 - val_loss: 0.4415 - val_accuracy: 0.8556
Epoch 56/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4588 - accuracy: 0.8240 - val_loss: 0.4291 - val_accuracy: 0.8556
Epoch 57/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4907 - accuracy: 0.8002 - val_loss: 0.4415 - val_accuracy: 0.8556
Epoch 58/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4857 - accuracy: 0.7790 - val_loss: 0.4548 - val_accuracy: 0.8444
Epoch 59/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4808 - accuracy: 0.8040 - val_loss: 0.4488 - val_accuracy: 0.8444
Epoch 60/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4726 - accuracy: 0.8040 - val_loss: 0.4431 - val_accuracy: 0.8444
Epoch 61/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4699 - accuracy: 0.7990 - val_loss: 0.4380 - val_accuracy: 0.8444
Epoch 62/100
81/81 [==============================] - 1s 7ms/step - loss: 0.4837 - accuracy: 0.8015 - val_loss: 0.4336 - val_accuracy: 0.8444
Epoch 63/100
81/81 [==============================] - 1s 7ms/step - loss: 0.4681 - accuracy: 0.8227 - val_loss: 0.4513 - val_accuracy: 0.8444
Epoch 64/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4694 - accuracy: 0.7940 - val_loss: 0.4292 - val_accuracy: 0.8222
Epoch 65/100
81/81 [==============================] - 1s 10ms/step - loss: 0.4875 - accuracy: 0.7928 - val_loss: 0.4497 - val_accuracy: 0.8556
Epoch 66/100
81/81 [==============================] - 1s 8ms/step - loss: 0.4829 - accuracy: 0.8040 - val_loss: 0.4537 - val_accuracy: 0.8444
Epoch 67/100
81/81 [==============================] - 1s 10ms/step - loss: 0.4798 - accuracy: 0.7890 - val_loss: 0.4536 - val_accuracy: 0.8444
Epoch 68/100
81/81 [==============================] - 1s 10ms/step - loss: 0.4770 - accuracy: 0.8027 - val_loss: 0.4446 - val_accuracy: 0.8444
Epoch 69/100
81/81 [==============================] - 1s 6ms/step - loss: 0.4950 - accuracy: 0.7878 - val_loss: 0.4686 - val_accuracy: 0.8444
Epoch 70/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4970 - accuracy: 0.7915 - val_loss: 0.4620 - val_accuracy: 0.8556
Epoch 71/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4754 - accuracy: 0.7965 - val_loss: 0.4444 - val_accuracy: 0.8222
Epoch 72/100
81/81 [==============================] - 0s 6ms/step - loss: 0.4768 - accuracy: 0.7978 - val_loss: 0.4502 - val_accuracy: 0.8556
Epoch 73/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4735 - accuracy: 0.7990 - val_loss: 0.4410 - val_accuracy: 0.8556
Epoch 74/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4754 - accuracy: 0.7915 - val_loss: 0.4452 - val_accuracy: 0.8333
Epoch 75/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4858 - accuracy: 0.7940 - val_loss: 0.4509 - val_accuracy: 0.8444
Epoch 76/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4729 - accuracy: 0.8177 - val_loss: 0.4483 - val_accuracy: 0.8444
Epoch 77/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4848 - accuracy: 0.8040 - val_loss: 0.4428 - val_accuracy: 0.8556
Epoch 78/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4664 - accuracy: 0.8040 - val_loss: 0.4491 - val_accuracy: 0.8444
Epoch 79/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4783 - accuracy: 0.8052 - val_loss: 0.4521 - val_accuracy: 0.8444
Epoch 80/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4758 - accuracy: 0.8027 - val_loss: 0.4467 - val_accuracy: 0.8222
Epoch 81/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4582 - accuracy: 0.8202 - val_loss: 0.4450 - val_accuracy: 0.8556
Epoch 82/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4653 - accuracy: 0.8040 - val_loss: 0.4501 - val_accuracy: 0.8333
Epoch 83/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4659 - accuracy: 0.7915 - val_loss: 0.4546 - val_accuracy: 0.8444
Epoch 84/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4559 - accuracy: 0.8052 - val_loss: 0.4464 - val_accuracy: 0.8556
Epoch 85/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4734 - accuracy: 0.8140 - val_loss: 0.4487 - val_accuracy: 0.8444
Epoch 86/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4803 - accuracy: 0.7853 - val_loss: 0.4656 - val_accuracy: 0.8444
Epoch 87/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4558 - accuracy: 0.8165 - val_loss: 0.4507 - val_accuracy: 0.8333
Epoch 88/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4724 - accuracy: 0.7890 - val_loss: 0.4568 - val_accuracy: 0.8444
Epoch 89/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4577 - accuracy: 0.8165 - val_loss: 0.4544 - val_accuracy: 0.8556
Epoch 90/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4620 - accuracy: 0.8065 - val_loss: 0.4346 - val_accuracy: 0.8444
Epoch 91/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4692 - accuracy: 0.8015 - val_loss: 0.4566 - val_accuracy: 0.8333
Epoch 92/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4647 - accuracy: 0.7990 - val_loss: 0.4544 - val_accuracy: 0.8444
Epoch 93/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4858 - accuracy: 0.7978 - val_loss: 0.4614 - val_accuracy: 0.8111
Epoch 94/100
81/81 [==============================] - 0s 4ms/step - loss: 0.4611 - accuracy: 0.7965 - val_loss: 0.4641 - val_accuracy: 0.8333
Epoch 95/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4708 - accuracy: 0.8027 - val_loss: 0.4651 - val_accuracy: 0.8333
Epoch 96/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4574 - accuracy: 0.8165 - val_loss: 0.4663 - val_accuracy: 0.8444
Epoch 97/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4890 - accuracy: 0.7915 - val_loss: 0.4719 - val_accuracy: 0.8111
Epoch 98/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4686 - accuracy: 0.8102 - val_loss: 0.4512 - val_accuracy: 0.8222
Epoch 99/100
81/81 [==============================] - 0s 3ms/step - loss: 0.4831 - accuracy: 0.8040 - val_loss: 0.4579 - val_accuracy: 0.8444
Epoch 100/100
81/81 [==============================] - 0s 5ms/step - loss: 0.4701 - accuracy: 0.7990 - val_loss: 0.4500 - val_accuracy: 0.8222
28/28 [==============================] - 0s 3ms/step - loss: 0.4348 - accuracy: 0.8418
Validation Accuracy: 84.18%
14/14 [==============================] - 0s 3ms/step

In [514]:

# Print accuracy
print(f"Validation Accuracy included in CSV: {validation_accuracy:.2%}")

Validation Accuracy included in CSV: 84.18%